version: "3"
services:
  wechat-audio-downloader:
    image: wechat-audio-downloader:latest
    container_name: audio-downloader
    environment:
      DOWNLOAD_PATH: /downloads
      LANG: en_US.UTF-8
    volumes:
    - ./downloads:/downloads
    ports:
    - "8091:8080"